name = "PressureLines"
uuid = "2c40e35c-2862-4264-896d-c2b616468a12"
version = "1.0.0-DEV"
authors = ["= <pjabardo@ipt.br> and contributors"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
SpecialFunctions = "2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
